### ISSUE TITLE
Построение графиков enum'ов.

### ISSUE THREAD

**Issue by LeKaitoW** [LeKaitoW/rdo-xtext#12]

**Comment by LeKaitoW** [comment]
На оси отмечаются все значения - и используемые, и не используемые.
![tnat4igkp9y](https://cloud.githubusercontent.com/assets/10632455/7510316/d13ddbb6-f4ab-11e4-91e4-d5a23715d2ba.jpg)

Стандартное прореживание значений оси JFreeChart'а:
![default](https://cloud.githubusercontent.com/assets/10632455/7510353/1e42b940-f4ac-11e4-9707-8e05f4d26d9f.jpg)

Кажется, что не нужно давать имя вертикальной оси, всё равно дублируется с легендой (если график один). Оставлять ли имя? Или убрать, пока не начну заниматься отображением нескольких графиков на одном чарте?
![_ _](https://cloud.githubusercontent.com/assets/10632455/7510412/bccaf33e-f4ac-11e4-9834-8e62211f75c4.jpg)

(А ещё на винде у JfreeChart'а умирает кириллица, пока что разбираюсь, как это пофиксить.)

**Comment by aurusov** [comment]
Выглядит отлично.

>Оставлять ли имя?

Не надо.

>Или убрать, пока не начну заниматься отображением нескольких графиков на одном чарте?

Кажется, что и тут не надо будет.

**Comment by LeKaitoW** [comment]
@aurusov 
Имя оси убрала.
Можно ли закрывать таску?

**Comment by aurusov** [comment]
Конечно. Ты можешь закрывать таски сама, по готовности.

**Comment by LeKaitoW** [comment]
Окончательный вариант шрифта:
![default](https://cloud.githubusercontent.com/assets/10632455/7515998/ed0b76b0-f4dc-11e4-91f5-3800fa4772a6.jpg)
