### ISSUE TITLE
Перемещение по графику вправо-влево, вверх-вниз

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/rdo-xtext#16]
Зависит от https://github.com/LeKaitoW/rdo-xtext/issues/18

**Comment by LeKaitoW** [comment]
@aurusov 
Добавлен слайдер для оси X. Работает и при нажатии на стрелки, и при нажатии слева-справа от слайдера, и при перетаскивании самого слайдера.
![default](https://cloud.githubusercontent.com/assets/10632455/7671296/4050c8ca-fcda-11e4-9b66-f253ec2574e7.jpg)

При зуме в процессе прогона модели не меняет ось Y. Стоит ли это исправлять?
![default](https://cloud.githubusercontent.com/assets/10632455/7671300/602f26dc-fcda-11e4-90d4-cab7f7660c2d.jpg)

**Comment by aurusov** [comment]
>При зуме в процессе прогона модели не меняет ось Y. (В момент зума максимальное значение по Y было равно единице.) Стоит ли это исправлять?

Добавилось значение с координатой по Y больше 1. Но т.к. был ручной зум, то автозум не сработал. Правильно понял ? Если да, то это и есть текущая задача - "вверх-вниз". Т.е. нужно добавить слайдер и по это оси. И второе - когда данные добавляются, то нижший слайдер менает изменяет свою ширину ? Для слайдеров не должно быть разницы. Их логика такова: документ изменился, но он не влезает в окно, давайтеп скролить. Если влезает, то слайдер скрывается.

**Comment by LeKaitoW** [comment]
> Правильно понял ?

Да.

> И второе - когда данные добавляются, то нижший слайдер изменяет свою ширину ?

Изменяет.

Ок, постараюсь вертикальный слайдер успеть добавить до вторника.

**Comment by aurusov** [comment]
Ой, так долго. Это сложно ? Мне кажется, что должно быть очень похоже на горизонтальный слайдер.

**Comment by aurusov** [comment]
(случайно закрыл таску)

**Comment by LeKaitoW** [comment]
Там что-то не очень понятное про задание координат и толщины слайдера. Про горизонтальный был пример, а вертикальный придётся методом тыка задавать.

**Comment by LeKaitoW** [comment]
@aurusov 

![default](https://cloud.githubusercontent.com/assets/10632455/7701449/43f3333c-fe38-11e4-8d6e-34f88246948d.png)
