### ISSUE TITLE
Добавить зум к графикам

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/rdo-xtext#18]
Решать в последовательности
- Использовать встроенные методы jFreeChart
- Руками определять выбранную область и выводить данные для неё из dataset'а

ZoomIn (+)
- Основан на выделение области вправо. Увеличивает только ось X. Если из коробки заработает автомасштаб по Y - тоже ничего. Но лучше сделать опционально через Shift + Mouse

ZoomOut (-)
- Основан на выделение влево. После чего показывается весь график целиком. Можно подумать над возвратом к пред. масштабу через Shift + Mouse.

Очень беспокоит ошибка выбора области мышкой, она смещена. Начать лучше именно с неё.

**Comment by LeKaitoW** [comment]
Проблема с ошибкой выбора области решилась использованием другого конструктора для ```ChartComposite```, который нашел @bogachev-pa.

Отключение зума по оси Y заняло одну строчку - вызовом метода ```setRangeZoomable(boolean)```.
Передевая в этот метод ```false```, зум теперь выглядит так: (курсор при выделении находился по оси Y примерно по центру)
![default](https://cloud.githubusercontent.com/assets/10632455/7669551/4dbf6dbe-fc89-11e4-9e99-822ab0bf92fd.png)
![2](https://cloud.githubusercontent.com/assets/10632455/7669558/b4ad0310-fc89-11e4-8ab0-c52d30d6d23f.png)

При этом зум по Y работает при выборе соответствующего пункта в выпадающем меню:
![default](https://cloud.githubusercontent.com/assets/10632455/7669560/ef2a2054-fc89-11e4-980b-59d246aee6ac.png)
![1](https://cloud.githubusercontent.com/assets/10632455/7669561/f1d33cf0-fc89-11e4-84e7-f305a23dfa25.png)

**Comment by LeKaitoW** [comment]
@aurusov 
UPD: Теперь зум по оси Y работает только при Shift + Mouse.
Кстати, zoom out это тоже задевает. Может, возвращение к предыдущему состоянию делать через Ctrl + Mouse? (Если это вообще возможно.)

**Comment by aurusov** [comment]
Очень круто, я прям радуюсь.
Да, можно через Ctrl + Mouse. Если не получится сделать быстро, то можно закрывать таску и без этого. Потому что сделана большая часть задачи.

**Comment by LeKaitoW** [comment]
Думаю, стоит сделать отдельную таску для zoom out, а эту закрыть.
