### ISSUE TITLE
Вариант внедрения пятнашек в RAO-XT

### ISSUE THREAD

**Issue by LeKaitoW** [LeKaitoW/rdo-xtext#21]
Вариант внедрения пятнашек в RAO-XT аналогичный пятнашкам в старом РДО: исходники одни, но есть возможность собирать без них. вариант внедрения пятнашек в RAO-XT аналогичный пятнашкам в старом РДО: исходники одни, но есть возможность собирать без них. При этом пятнашки не будут jar'ником - иначе могут возникать проблемы с вызовом кода РДО из jar пятнашек.
Исходники пятнашек будут просто в отдельном package, наряду с ui и lib.

**Comment by LeKaitoW** [comment]
@aurusov 
@k-alexandrovsky
@bogachev-pa

**Comment by aurusov** [comment]
>но есть возможность собирать без них

Ради чего так упираться ?

>При этом пятнашки не будут jar'ником - иначе могут возникать проблемы с вызовом кода РДО из jar пятнашек.

1. Объясните мне сложности вызова
2. Разве пакет не будет компилироваться в jar ?

**Comment by LeKaitoW** [comment]
>Ради чего так упираться ?

Вы же говорили, что пятнашки не должны быть в основном релизе.

> 1. Объясните мне сложности вызова

Пятнашкам ведь надо дергать классы рдо (создавать модель, запускать прогон и т.д.), а разве мы сможем это делать из внешнего jar'ника? Откуда он будет знать об этих классах рдо?

> 2. Разве пакет не будет компилироваться в jar ?

Но зачем?

**Comment by aurusov** [comment]
>Вы же говорили, что пятнашки не должны быть в основном релизе.

Каким образом можно будет включать/отключать сборку пятнашек ?

**Comment by LeKaitoW** [comment]
В версии а-ля rao1.3.0_game5 у нас будут указаны зависимости от классов пятнашек (сами кассы будут собраны), а в версии rao1.3.0  таких зависимостей не будет (соответственно, классы не собраны).
По аналогии с версиями anylogic.

**Comment by aurusov** [comment]
Это будет в виде двух бранчей в репозитории ? Или какие-то настроки проекта, которые можно/нужно будет менять ?

PS: Версии у нас вот [такие](https://github.com/aurusov/rdo-xtext/releases).

**Comment by LeKaitoW** [comment]
Настройка при сборке.

**Comment by aurusov** [comment]
Вопросы по этой таски еще остались ?

**Comment by LeKaitoW** [comment]
Если такой вариант подходит, то вопросов нет. :)

**Comment by LeKaitoW** [comment]
Обсудили с Кириллом и Пашей и пришли к выводу, что правильнее будет такая схема: релиз РДО как jar, а пятнашки отдельный плагин, зависящий от jar РДО (это будет прописано в dependency).

**Comment by aurusov** [comment]
>На данный момент получилось сделать экспорт РДО как jar и установить его как плагин в обычный эклипс (открыв перспективу, можно создавать и прогонять модели и т.д.).
Стоит ли это дописать в инструкцию? И заодно написать вторую инструкцию для пользователей, как добавить плагин РДО (уже в виде jar) в эклипс?

Не понял, в чем разница между этими вариантами. Как минимум одну инструкцию написать надо. Но это тема другой таски. Эту закрывай.

**Comment by aurusov** [comment]
А про разницу пояснишь ?

**Comment by LeKaitoW** [comment]
Я так поняла, вы имеете в виду разницу между вариантом, для которого открывалась таска и новым?
В первом варианте исходники пятнашек и РДО – в одном репозитории, а во втором – в разных.

**Comment by aurusov** [comment]
Еще больше запутался. Давай с самого начала. Вот вы обсудили
>Обсудили с Кириллом и Пашей и пришли к выводу, что правильнее будет такая схема: релиз РДО как jar, а пятнашки отдельный плагин, зависящий от jar РДО (это будет прописано в dependency).

Вроде как вариант один. А потом ты про какие два варианта говоришь. О чём они ?

**Comment by LeKaitoW** [comment]
Я вас не так поняла.
>Обсудили с Кириллом и Пашей и пришли к выводу, что правильнее будет такая схема: релиз РДО как jar, а пятнашки отдельный плагин, зависящий от jar РДО (это будет прописано в dependency).
На данный момент получилось сделать экспорт РДО как jar и установить его как плагин в обычный эклипс (открыв перспективу, можно создавать и прогонять модели и т.д.).

Это все один вариант внедрения, а дальше я говорю про две инструкция: для разработчика и для пользователя.

**Comment by aurusov** [comment]
Ага, теперь сошлось. Спасибо.
