### ISSUE TITLE
Инструкция для подготовки бинарного релиза РДО

### ISSUE THREAD

**Issue by LeKaitoW** [LeKaitoW/rdo-xtext#22]
`File` > `Export` > `Plug-in Development` > `Deployable Plug-ins and features` > `Next` > `Select All` > `Destination` > `Directory = .../eclipse/dropins` > `Finish`

*[!] If errors occured during the export operation, try to install or update PDE:
`Help` > `Eclipse Marketplace...` > `Search` > `Find: = Eclipse PDE` > `Install\Update`*

Получается, такие экспорты нужно будет делать при каждом релизе?

И нужно ли коммитить эту часть инструкции?

**Comment by aurusov** [comment]
Чтобы было понятнее, распиши кейсы:
- последовательность действий подготовки нового релиза разработчиком
- последовательность действий работы с эклипсом пользователя, когда
 - эклипс скачивается с нашего сайта как архив, уже с плагином
 - эклипс скачивается с офф. сайта, и плагин доставляется руками
 - эклипс уже с плагином, но пользователь хочет обновить РДО руками

Может еще какие варианты надумаешь. И твой пример для кого ? Разработчика, перетекающего в пользователя. Прошу ответить на все вопросы, а не только последний.

**Comment by LeKaitoW** [comment]
Так как таска про экспорт, соответственно, она не может быть связана с пользователем. Расписать все кейсы тут, чтобы не плодить таски?

**Comment by LeKaitoW** [comment]
1. Подготовка нового релиза разработчиком:
- `File` > `Export` > `Deployable Plug-ins and features`
- `Select All`

*[!] If errors occured during the export operation, try to install or update PDE:
`Help` > `Eclipse Marketplace...` > `Search` > `Find: = Eclipse PDE` > `Install\Update`*
- `Destination` > `Directory = .../eclipse/dropins`

2. Эклипс скачивается с нашего сайта как архив, уже с плагином:
- Run Eclipse
- `Window` > `Open Perspective` > 'Other' > `RDO`

**Comment by aurusov** [comment]
>1 . Подготовка нового релиза разработчиком:

Допиши действия по созданию архива. Для винды и линуха. Ты вообще этим сама занимаешься или тебе ребята помогают ?

>2 . Эклипс скачивается с нашего сайта как архив, уже с плагином:

Выглядит законченным, последний пункт с тремя точками не нужен

>3 . Эклипс с офф. сайта, плагин доставляется руками:
>4 . Эклипс с плагином, но пользователь хочет обновить РДО руками:

Тут просто жду. Примеры нужны для двух операционок. Ну и последний пункт нафиг.

**Comment by LeKaitoW** [comment]
>Допиши действия по созданию архива.

Там как раз описан экспорт РДО в jar. То есть в этой самой `Directory = .../eclipse/dropins` мы получим 4 архива. В винде вчера ошибка какая-то выпала, сегодня постараюсь разобраться.
Ребята помогают в основном по теоретическим вопросам.

**Comment by aurusov** [comment]
>Допиши действия по созданию архива.

Имель в виду то, что потом будет скачиваться с нашего сайта. Нужен мостик от 1 к 2.

**Comment by LeKaitoW** [comment]
Хорошо. Вечером постараюсь дописать все инструкции.

**Comment by aurusov** [comment]
Инструкция для 2, 3 и 4 в рамках этой задачи https://github.com/aurusov/rdo-xtext/issues/26

**Comment by aurusov** [comment]
В рамках этой таски давай оставим только (1)

**Comment by LeKaitoW** [comment]
- `File` > `Export` > `Plug-in Development` > `Deployable Plug-ins and features` > `Next` > `Select All` > `Destination` > `Directory` = set directory for export > `Finish`

*[!] If errors occured during the export operation, try to install or update PDE:
`Help` > `Eclipse Marketplace...` > `Search` > `Find: = Eclipse PDE` > `Install\Update`*
- Put jars into `.../eclipse/dropins/plugins`
- Restart Eclipse
-  `Window` > `Open Perspective` > `Other` > `Rao`

**Comment by aurusov** [comment]
Инструкция есть. Можно закрывать. Автосборки нет, но она в другой таске https://github.com/aurusov/rdo-xtext/issues/131
