### ISSUE TITLE
Встроить вызов и построение графиков в РДО

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/rdo-xtext#4]
На основании чего можно строить графики
* По параметру любого ресурса
* У операций и клавиатурных операций могут быть
  * количество одновременно запущенных
* По собираемым показателям
  * не помню что, надо дописать

**Comment by LeKaitoW** [comment]
Сейчас возможно построение графиков:
* По параметру любого ресурса
* У операций и клавиатурных операций
  * по количеству одновременно запущенных
* По собираемым показателям
  * все, кроме ```get_value```
