### ISSUE TITLE
Plot disabling

### ISSUE THREAD

**Issue by LeKaitoW** [LeKaitoW/rdo-xtext#8]
```Plot``` сейчас подсвечен для параметров ресурсов и для всех результатов.
Надо добавить проверку на ```get_value```, чтобы отключать для них ```Plot```. (Сейчас эта проверка доступна тоько через ```entry```, парсить из ui не получится - нет доступа к ```Tracer.prepareBufferForReading()```. @bogachev-pa планирует добавить возможность такой проверки из индекса.
![plot1](https://cloud.githubusercontent.com/assets/10632455/7182132/78d94844-e460-11e4-9b0f-60b7fad61f6a.jpg)
![plot2](https://cloud.githubusercontent.com/assets/10632455/7182133/78db5c2e-e460-11e4-8702-a4978db84267.jpg)

**Comment by bogachev-pa** [comment]
Все получается немного сложнее. Получить тип результата можно и сейчас:
Номер результата хранится в индексе, а по номеру можно достать структуру модели:
```java
Simulator.getModelStructureCache().resultsInfo.get(number).valueType;
```

Но проблема в том, что сейчас у нас получается много дублирования данных.
Данные в `ModelStructureCache` дублируют структуру модели, которую мы храним в `JSON`. Изначально это использовалось для более быстрого доступа к структуре из трассировщика, но теперь разные компоненты используют кто структуру джейсона, кто кэш. В общем, надо прибраться как-то в этом бардаке.

Засорять еще и индексы той же инфой не очень хочется. Наверное, стоит как-то унифицировать содержимое индексов. Как именно, пока точно не продумал.

**Comment by bogachev-pa** [comment]
Насчет типа результата я ошибся, в кэше структуры сейчас хранится только тип его значения.

Так что я пока добавил тип результата в его индекс.
